export const THIRD_PARTY_MODULES_SPECIAL_WORD = '<THIRD_PARTY_MODULES>';
export const NAMED_IMPORT_PLACEHOLDER_SPECIAL_WORD =
	'<NAMED_IMPORT_PLACEHOLDER>';
export const GROUP_SEPARATOR = '\n\n';
export const IMPORT_SEPARATOR = '\n';
